// @TASK P3-R6-T2 + P3-R7-T2 - README Writer + Landing Deployer tests
// @TEST tests/generators-writers.test.ts

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { rmSync } from 'node:fs';
import { writeReadme, deployLandingPage } from '../src/generators/index.js';

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await mkdtemp(join(tmpdir(), 'nerdspecs-test-'));
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

describe('writeReadme', () => {
  it('writes README.md and returns correct path and line count', async () => {
    const content = '# Hello\n\nWorld\n<!-- Generated by NerdSpecs -->\n';
    const result = await writeReadme(tmpDir, content);
    expect(result.path).toBe(join(tmpDir, 'README.md'));
    const written = await readFile(result.path, 'utf8');
    expect(written).toBe(content);
    expect(result.lines).toBe(written.split('\n').length);
  });

  it('prepends NerdSpecs content when no marker in existing README', async () => {
    const existing = '# My Custom Docs\n\nExisting content here.\n';
    await writeFile(join(tmpDir, 'README.md'), existing, 'utf8');
    const generated = '# Generated\n<!-- Generated by NerdSpecs -->\n';
    await writeReadme(tmpDir, generated);
    const written = await readFile(join(tmpDir, 'README.md'), 'utf8');
    expect(written).toContain('# Generated');
    expect(written).toContain('# My Custom Docs');
    expect(written).toContain('Existing content here.');
  });

  it('replaces only NerdSpecs section when marker exists', async () => {
    const existing = '# My Custom Docs\n\n<!-- Generated by NerdSpecs -->\nOld generated content\n';
    await writeFile(join(tmpDir, 'README.md'), existing, 'utf8');
    const generated = '# Generated\n<!-- Generated by NerdSpecs -->\nNew content\n';
    await writeReadme(tmpDir, generated);
    const written = await readFile(join(tmpDir, 'README.md'), 'utf8');
    expect(written).toContain('# My Custom Docs');
    expect(written).toContain('New content');
    expect(written).not.toContain('Old generated content');
  });

  it('normalizes README path inside the project root', async () => {
    const result = await writeReadme(join(tmpDir, '.', 'nested', '..'), '# Normalized\n');
    expect(result.path).toBe(join(tmpDir, 'README.md'));
  });
});

describe('deployLandingPage', () => {
  it('writes docs/index.html and returns correct path and URL', async () => {
    const html = '<html><body>Hello</body></html>';
    const result = await deployLandingPage(tmpDir, html, 'myorg--myrepo');
    expect(result.path).toBe(join(tmpDir, 'docs', 'index.html'));
    expect(result.url).toBe('https://myorg.github.io/myrepo/');
    const written = await readFile(result.path, 'utf8');
    expect(written).toBe(html);
  });

  it('creates docs/ directory if it does not exist', async () => {
    const html = '<html></html>';
    const result = await deployLandingPage(tmpDir, html, 'owner--repo');
    const written = await readFile(result.path, 'utf8');
    expect(written).toBe(html);
  });

  it('derives correct GitHub Pages URL from repoSlug', async () => {
    const { url } = await deployLandingPage(tmpDir, '', 'johndoe--my-project');
    expect(url).toBe('https://johndoe.github.io/my-project/');
  });

  it('normalizes docs path inside the project root', async () => {
    const result = await deployLandingPage(join(tmpDir, '.', 'site', '..'), '<html></html>', 'owner--repo');
    expect(result.path).toBe(join(tmpDir, 'docs', 'index.html'));
  });
});
