// @TASK P3-R6-T1 - README Template Engine Tests
// @TEST tests/readme-template.test.ts

import { describe, it, expect } from 'vitest';
import { generateReadme, type ReadmeData } from '../src/generators/readme-template.js';

function baseData(overrides: Partial<ReadmeData> = {}): ReadmeData {
  return {
    project_name: 'MyApp',
    summary: 'A simple tool.',
    language_mode: 'en',
    tech_stack: { language: 'TypeScript', frameworks: ['Express'], apis: ['REST'], services: ['S3'] },
    sections: { hero: true, plain_explanation: true, how_to_use: true, tech_stack: true, installation: true },
    ...overrides,
  };
}

describe('generateReadme', () => {
  it('en mode — all section headings in English', () => {
    const out = generateReadme(baseData({ language_mode: 'en' }));
    expect(out).toContain('What is this?');
    expect(out).toContain('Who is this for?');
    expect(out).toContain('How to use');
    expect(out).not.toContain('이게 뭐예요?');
  });

  it('ko mode — section headings in Korean', () => {
    const out = generateReadme(baseData({ language_mode: 'ko' }));
    expect(out).toContain('이게 뭐예요?');
    expect(out).toContain('누구를 위한 건가요?');
    expect(out).toContain('사용 방법');
    expect(out).not.toContain('What is this?');
  });

  it('both mode — bilingual structure with --- separator', () => {
    const out = generateReadme(baseData({ language_mode: 'both' }));
    expect(out).toContain('What is this?');
    expect(out).toContain('이게 뭐예요?');
    expect(out).toContain('---');
  });

  it('section toggle — tech_stack disabled removes it from output', () => {
    const out = generateReadme(baseData({
      sections: { hero: true, plain_explanation: true, how_to_use: true, tech_stack: false, installation: true },
    }));
    expect(out).not.toContain('<details>');
  });

  it('footer comment always present', () => {
    const out = generateReadme(baseData({ language_mode: 'ko' }));
    expect(out).toContain('<!-- Generated by NerdSpecs -->');
  });

  it('collapsible tech stack uses <details> tag', () => {
    const out = generateReadme(baseData());
    expect(out).toContain('<details>');
    expect(out).toContain('<summary>Tech Stack</summary>');
    expect(out).toContain('</details>');
  });

  it('hero section has project name as H1', () => {
    const out = generateReadme(baseData({ project_name: 'MyApp' }));
    expect(out).toMatch(/^# MyApp/);
  });
});
