// @TASK P3-R6-T1 - README Template Engine
// @SPEC docs/planning/06-tasks.md#readme-template

export interface ReadmeData {
  project_name: string;
  summary: string;
  motivation?: string;
  tech_stack: { language: string; frameworks: string[]; apis: string[]; services: string[] };
  language_mode: 'en' | 'ko' | 'zh' | 'both';
  sections: {
    hero: boolean;
    plain_explanation: boolean;
    how_to_use: boolean;
    tech_stack: boolean;
    installation: boolean;
  };
}

const LABELS = {
  en: {
    whatIsThis: 'What is this?',
    whoIsItFor: 'Who is this for?',
    installation: 'Installation',
    howToUse: 'How to use',
    techStack: 'Tech Stack',
  },
  ko: {
    whatIsThis: '이게 뭐예요?',
    whoIsItFor: '누구를 위한 건가요?',
    installation: '설치',
    howToUse: '사용 방법',
    techStack: '기술 스택',
  },
  zh: {
    whatIsThis: '这是什么？',
    whoIsItFor: '适合谁使用？',
    installation: '安装',
    howToUse: '使用方法',
    techStack: '技术栈',
  },
};

function heroSection(data: ReadmeData): string {
  if (!data.sections.hero) return '';
  return `# ${data.project_name}\n\n${data.summary}\n`;
}

function plainExplanationSection(data: ReadmeData): string {
  if (!data.sections.plain_explanation) return '';
  const en = `## ${LABELS.en.whatIsThis}\n\n${data.summary}`;
  const ko = `## ${LABELS.ko.whatIsThis}\n\n${data.summary}`;
  if (data.language_mode === 'en') return en + '\n';
  if (data.language_mode === 'ko') return ko + '\n';
  return `${en}\n\n---\n\n${ko}\n`;
}

function audienceForStack(lang: string): { en: string; ko: string } {
  const lower = lang.toLowerCase();
  if (lower === 'python') return { en: 'Data scientists and backend developers.', ko: '데이터 과학자 및 백엔드 개발자.' };
  if (lower === 'go') return { en: 'Backend engineers who need high performance.', ko: '고성능이 필요한 백엔드 엔지니어.' };
  return { en: 'Developers and technical teams.', ko: '개발자 및 기술 팀.' };
}

function whoIsItForSection(data: ReadmeData): string {
  const audience = audienceForStack(data.tech_stack.language);
  const en = `## ${LABELS.en.whoIsItFor}\n\n${audience.en}`;
  const ko = `## ${LABELS.ko.whoIsItFor}\n\n${audience.ko}`;
  if (data.language_mode === 'en') return en + '\n';
  if (data.language_mode === 'ko') return ko + '\n';
  return `${en}\n\n---\n\n${ko}\n`;
}

function installCommand(lang: string): string {
  const lower = lang.toLowerCase();
  if (lower === 'python') return 'pip install <package>';
  if (lower === 'go') return 'go get <module>';
  return 'npm install';
}

function usageCommand(lang: string): string {
  const lower = lang.toLowerCase();
  if (lower === 'python') return 'python main.py';
  if (lower === 'go') return 'go run .';
  return 'npm run dev';
}

function installationSection(data: ReadmeData): string {
  if (!data.sections.installation) return '';
  const cmd = installCommand(data.tech_stack.language);
  const label = data.language_mode === 'ko' ? LABELS.ko.installation : LABELS.en.installation;
  return `## ${label}\n\n\`\`\`bash\n${cmd}\n\`\`\`\n`;
}

function howToUseSection(data: ReadmeData): string {
  if (!data.sections.how_to_use) return '';
  const cmd = usageCommand(data.tech_stack.language);
  const label = data.language_mode === 'ko' ? LABELS.ko.howToUse : LABELS.en.howToUse;
  return `## ${label}\n\n\`\`\`bash\n${cmd}\n\`\`\`\n`;
}

function techStackList(ts: ReadmeData['tech_stack']): string {
  const items: string[] = [`- **Language**: ${ts.language}`];
  if (ts.frameworks.length > 0) items.push(`- **Frameworks**: ${ts.frameworks.join(', ')}`);
  if (ts.apis.length > 0) items.push(`- **APIs**: ${ts.apis.join(', ')}`);
  if (ts.services.length > 0) items.push(`- **Services**: ${ts.services.join(', ')}`);
  return items.join('\n');
}

function techStackSection(data: ReadmeData): string {
  if (!data.sections.tech_stack) return '';
  const label = data.language_mode === 'ko' ? LABELS.ko.techStack : LABELS.en.techStack;
  const body = techStackList(data.tech_stack);
  return `<details><summary>${label}</summary>\n\n${body}\n\n</details>\n`;
}

const NERD_LOGO = `
---

<div align="center">
  <pre>
   ╭─────╮ ╭─────╮
   │ ●   │─│   ● │
   ╰─────╯ ╰─────╯
  </pre>
  <sub>Made with <a href="https://www.npmjs.com/package/nerdspecs">NerdSpecs</a> — Put on nerd glasses and the project becomes visible.</sub>
</div>
`;

const FOOTER = NERD_LOGO + '\n<!-- Generated by NerdSpecs -->';

export function generateReadme(data: ReadmeData): string {
  const parts = [
    heroSection(data),
    plainExplanationSection(data),
    whoIsItForSection(data),
    installationSection(data),
    howToUseSection(data),
    techStackSection(data),
    FOOTER,
  ].filter(Boolean);

  return parts.join('\n') + '\n';
}
