// @TASK P3-R6-T2 - README Writer
// @SPEC docs/planning/06-tasks.md#readme-writer

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';

const execAsync = promisify(exec);

const MARKER = '<!-- Generated by NerdSpecs -->';

async function readExisting(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch {
    return null;
  }
}

function mergeContent(existing: string, generated: string): string {
  const idx = existing.indexOf(MARKER);
  if (idx === -1) return generated + '\n' + existing;
  return existing.slice(0, idx) + generated;
}

export async function writeReadme(
  projectDir: string,
  content: string,
): Promise<{ lines: number; path: string }> {
  const path = join(projectDir, 'README.md');
  const existing = await readExisting(path);
  const final = existing ? mergeContent(existing, content) : content;
  await writeFile(path, final, 'utf8');
  const lines = final.split('\n').length;
  return { lines, path };
}

export async function commitReadme(
  projectDir: string,
  message = 'docs: update README via NerdSpecs',
): Promise<boolean> {
  try {
    await execAsync('git add README.md && git commit -m "' + message + '"', { cwd: projectDir });
    return true;
  } catch {
    return false;
  }
}
