// @TEST P3-S8-T1 - README Spec Compliance
// @IMPL src/generators/readme-template.ts
// @SPEC specs/screens/generated-readme.yaml

import { describe, it, expect } from 'vitest';
import { generateReadme, type ReadmeData } from '../../src/generators/readme-template.js';

function sampleData(overrides: Partial<ReadmeData> = {}): ReadmeData {
  return {
    project_name: 'SpecTestApp',
    summary: 'A tool that does something useful.',
    motivation: 'Non-developers need readable docs.',
    language_mode: 'en',
    tech_stack: {
      language: 'TypeScript',
      frameworks: ['Express', 'Vitest'],
      apis: ['GitHub API'],
      services: ['S3'],
    },
    sections: {
      hero: true,
      plain_explanation: true,
      how_to_use: true,
      tech_stack: true,
      installation: true,
    },
    ...overrides,
  };
}

// ─── spec: hero_block (position: top) ────────────────────────────────────────
describe('spec: hero_block', () => {
  it('contains H1 with project name', () => {
    const out = generateReadme(sampleData({ project_name: 'SpecTestApp' }));
    expect(out).toMatch(/^# SpecTestApp/m);
  });

  it('H1 is the very first line (position: top)', () => {
    const out = generateReadme(sampleData({ project_name: 'TopFirst' }));
    expect(out.trimStart()).toMatch(/^# TopFirst/);
  });

  it('summary appears in hero block', () => {
    const out = generateReadme(sampleData({ summary: 'Unique summary text 12345' }));
    expect(out).toContain('Unique summary text 12345');
  });
});

// ─── spec: plain_explanation (What is this? / Who is it for?) ────────────────
describe('spec: plain_explanation section', () => {
  it('en mode — plain explanation heading in English', () => {
    const out = generateReadme(sampleData({ language_mode: 'en' }));
    expect(out).toContain('What is this?');
  });

  it('ko mode — plain explanation heading in Korean', () => {
    const out = generateReadme(sampleData({ language_mode: 'ko' }));
    expect(out).toContain('이게 뭐예요?');
  });

  it('both mode — both EN and KO explanation headings present', () => {
    const out = generateReadme(sampleData({ language_mode: 'both' }));
    expect(out).toContain('What is this?');
    expect(out).toContain('이게 뭐예요?');
  });

  it('plain_explanation disabled — section absent from output', () => {
    const out = generateReadme(
      sampleData({
        sections: {
          hero: true,
          plain_explanation: false,
          how_to_use: true,
          tech_stack: true,
          installation: true,
        },
      })
    );
    expect(out).not.toContain('What is this?');
    expect(out).not.toContain('이게 뭐예요?');
  });
});

// ─── spec: tech_details — collapsible with <details> tag ─────────────────────
describe('spec: tech_details collapsible section', () => {
  it('uses <details> tag (GitHub collapsible)', () => {
    const out = generateReadme(sampleData());
    expect(out).toContain('<details>');
  });

  it('uses <summary> tag inside <details>', () => {
    const out = generateReadme(sampleData());
    expect(out).toContain('<summary>');
  });

  it('closes with </details>', () => {
    const out = generateReadme(sampleData());
    expect(out).toContain('</details>');
  });

  it('tech stack disabled — no <details> in output', () => {
    const out = generateReadme(
      sampleData({
        sections: {
          hero: true,
          plain_explanation: true,
          how_to_use: true,
          tech_stack: false,
          installation: true,
        },
      })
    );
    expect(out).not.toContain('<details>');
  });

  it('lists language in tech stack', () => {
    const out = generateReadme(sampleData({ tech_stack: { language: 'Go', frameworks: [], apis: [], services: [] } }));
    expect(out).toContain('Go');
  });
});

// ─── spec: nerdspecs_footer — HTML comment ───────────────────────────────────
describe('spec: nerdspecs_footer HTML comment', () => {
  it('footer comment present in en mode', () => {
    const out = generateReadme(sampleData({ language_mode: 'en' }));
    expect(out).toContain('<!-- Generated by NerdSpecs -->');
  });

  it('footer comment present in ko mode', () => {
    const out = generateReadme(sampleData({ language_mode: 'ko' }));
    expect(out).toContain('<!-- Generated by NerdSpecs -->');
  });

  it('footer comment present in both mode', () => {
    const out = generateReadme(sampleData({ language_mode: 'both' }));
    expect(out).toContain('<!-- Generated by NerdSpecs -->');
  });

  it('footer is an HTML comment (starts with <!--)', () => {
    const out = generateReadme(sampleData());
    const footerIdx = out.indexOf('<!-- Generated by NerdSpecs -->');
    expect(footerIdx).toBeGreaterThan(-1);
    // must end with -->
    expect(out.slice(footerIdx)).toMatch(/<!-- Generated by NerdSpecs -->/);
  });
});

// ─── spec: bilingual structure (language=both) ───────────────────────────────
describe('spec: bilingual structure (language_mode=both)', () => {
  it('both mode — EN and KO sections separated by ---', () => {
    const out = generateReadme(sampleData({ language_mode: 'both' }));
    expect(out).toContain('---');
  });

  it('both mode — Who is it for appears in EN', () => {
    const out = generateReadme(sampleData({ language_mode: 'both' }));
    expect(out).toContain('Who is this for?');
  });

  it('both mode — Who is it for appears in KO', () => {
    const out = generateReadme(sampleData({ language_mode: 'both' }));
    expect(out).toContain('누구를 위한 건가요?');
  });

  it('en mode — no Korean headings', () => {
    const out = generateReadme(sampleData({ language_mode: 'en' }));
    expect(out).not.toContain('이게 뭐예요?');
    expect(out).not.toContain('누구를 위한 건가요?');
  });

  it('ko mode — no English section headings', () => {
    const out = generateReadme(sampleData({ language_mode: 'ko' }));
    expect(out).not.toContain('What is this?');
    expect(out).not.toContain('Who is this for?');
  });
});

// ─── spec: placeholder fallback (empty project_name / summary) ───────────────
describe('spec: placeholder fallback for empty fields', () => {
  it('empty summary does not produce double blank lines / bare empty heading', () => {
    const out = generateReadme(sampleData({ summary: '' }));
    // output must still contain H1 with project name
    expect(out).toMatch(/^# SpecTestApp/m);
  });
});
